export const userData = [
    {
      month: 'Jan',
      numberOfVisitors: 27,
    },
    {
      month: 'Feb',
      numberOfVisitors: 19,
    },
    {
      month: 'Mar',
      numberOfVisitors: 32,
    },
    {
      month: 'Apr',
      numberOfVisitors: 25,
    },
    {
      month: 'May',
      numberOfVisitors: 9,
    },
    {
      month: 'Jun',
      numberOfVisitors: 38,
    },
    {
      month: 'Jul',
      numberOfVisitors: 22,
    },
    {
      month: 'Aug',
      numberOfVisitors: 9,
    },
    {
      month: 'Sep',
      numberOfVisitors: 41,
    },
    {
      month: 'Oct',
      numberOfVisitors: 14,
    },
    {
      month: 'Nov',
      numberOfVisitors: 35,
    },
    {
      month: 'Dec',
      numberOfVisitors: 49,
    },
  ];


  export const hostRows = [
    {
      id: 1,
      name: 'Jon Snow',
      email: 'jonsnow@gmail.com',
      company: 'Eagles Consult',
      host: 'Kevin Keagan',
      sign_in: 'Feb 24, 22 | 09:05',
      sign_out: 'Feb 24, 22 | 10:45',
      status: 'checked in',
    },
    {
      id: 2,
      name: 'Jon Snow',
      email: 'jonsnow@gmail.com',
      company: 'Eagles Consult',
      host: 'Kevin Keagan',
      sign_in: 'Feb 24, 22 | 09:05',
      sign_out: 'Feb 24, 22 | 10:45',
      status: 'checked in',
    },
    {
      id: 3,
      name: 'Jon Snow',
      email: 'jonsnow@gmail.com',
      company: 'Eagles Consult',
      host: 'Kevin Keagan',
      sign_in: 'Feb 24, 22 | 09:05',
      sign_out: 'Feb 24, 22 | 10:45',
      status: 'checked out',
    },
    {
      id: 4,
      name: 'Jon Snow',
      email: 'jonsnow@gmail.com',
      company: 'Eagles Consult',
      host: 'Kevin Keagan',
      sign_in: 'Feb 24, 22 | 09:05',
      sign_out: 'Feb 24, 22 | 10:45',
      status: 'checked in',
    },
    {
      id: 5,
      name: 'Jon Snow',
      email: 'jonsnow@gmail.com',
      company: 'Eagles Consult',
      host: 'Kevin Keagan',
      sign_in: 'Feb 24, 22 | 09:05',
      sign_out: 'Feb 24, 22 | 10:45',
      status: 'checked out',
    },
    {
      id: 6,
      name: 'Jon Snow',
      email: 'jonsnow@gmail.com',
      company: 'Eagles Consult',
      host: 'Kevin Keagan',
      sign_in: 'Feb 24, 22 | 09:05',
      sign_out: 'Feb 24, 22 | 10:45',
      status: 'checked out',
    },
    {
      id: 7,
      name: 'Jon Snow',
      email: 'jonsnow@gmail.com',
      company: 'Eagles Consult',
      host: 'Kevin Keagan',
      sign_in: 'Feb 24, 22 | 09:05',
      sign_out: 'Feb 24, 22 | 10:45',
      status: 'checked out',
    },
    {
      id: 8,
      name: 'Jon Snow',
      email: 'jonsnow@gmail.com',
      company: 'Eagles Consult',
      host: 'Kevin Keagan',
      sign_in: 'Feb 24, 22 | 09:05',
      sign_out: 'Feb 24, 22 | 10:45',
      status: 'checked out',
    },
    {
      id: 9,
      name: 'Jon Snow',
      email: 'jonsnow@gmail.com',
      company: 'Eagles Consult',
      host: 'Kevin Keagan',
      sign_in: 'Feb 24, 22 | 09:05',
      sign_out: 'Feb 24, 22 | 10:45',
      status: 'checked out',
    },
  ];